projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-gem
      remote: m165437
      revision: main
      # Adding a path ensures it stays in its own folder 
      # and doesn't bleed into the main board search path incorrectly
      path: boards/shields/nice-view-gem
